### ISSUE TITLE
Speaker's dashboard

### ISSUE THREAD

**Issue by ndeloof** [cfpio/front-proposals#8]
![speaker dashboard](https://cloud.githubusercontent.com/assets/132757/15394283/509db1ba-1dd2-11e6-9479-f15b56569e79.png)

Show proposals, with icons for state (draft or submitted) and comments

**Comment by alvinberthelot** [comment]
Je vais m'occuper de cette vue là, c'est celle qui me semble la plus simple, ça me permettra de rentrer "tranquille" sur le projet.
